### ISSUE TITLE
Literówka w Example usage README.md

### ISSUE THREAD

**Issue by goodpl** [PiotrMachowski/Home-Assistant-custom-components-iMPK#1]
README.md jest literówka, przy sensor pierwsze wystąpienie lines: powinno być stops:

```
binary_sensor:
  - platform: impk
    monitored_conditions:
      - news
sensor:
  - platform: impk
    lines: 
      - id: 120820
      - id: 124202
        lines:
          - "D"
          - "131"
      - id: 124202
        name: "REJA"
        directions:
          - "REJA"
```
Powinno być
Example usage
```
binary_sensor:
  - platform: impk
    monitored_conditions:
      - news
sensor:
  - platform: impk
    stops:
      - id: 120820
      - id: 124202
        lines:
          - "D"
          - "131"
      - id: 124202
        name: "REJA"
        directions:
          - "REJA"
```

Przepraszam, że nie umiem inaczej tego zgłosić,
Pozdrawiam i dziękuję za ten i inne dodatki!
